//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAppSqlDb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MatchBuyertoSellers_Result> MatchBuyertoSellers(Nullable<int> zipcode, string item_needed, Nullable<int> buyerID)
        {
            var zipcodeParameter = zipcode.HasValue ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(int));
    
            var item_neededParameter = item_needed != null ?
                new ObjectParameter("item_needed", item_needed) :
                new ObjectParameter("item_needed", typeof(string));
    
            var buyerIDParameter = buyerID.HasValue ?
                new ObjectParameter("BuyerID", buyerID) :
                new ObjectParameter("BuyerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MatchBuyertoSellers_Result>("MatchBuyertoSellers", zipcodeParameter, item_neededParameter, buyerIDParameter);
        }
    }
}
